---
title       : Text Analysis App
subtitle    : Course Developing Data Products
author      : Igor Goltsov <riversy@gmail.com>
job         :
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : [bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## The idea

The app is based on the work of **Fereshteh Karimeddini** [Words Cloud][1]. In the other hand it was also inspired by the book of **Matthew L. Jockers** [Text Analysis with R for Students of Literature][2] about how to use data analysis in the literature science.

This app allows to make brief analysis of two literature works:
- Sense and Sensibility *by Jane Austen*;
- Moby Dick; or The Whale *by Herman Melville*.

User may choose the book for analysis and select the quantity of top used words you need. These words will be used to build **Words Cloud**. App will also build **Per Chapter Usage** bar plot for each of these words. This might be interesting for literature scientists to get in how author used words across the novel.


  [1]: http://shiny.rstudio.com/gallery/word-cloud.html "Words Cloud"
  [2]: https://www.springer.com/us/book/9783319031637#aboutBook "Text Analysis with R for Students of Literature"


--- .class #id

## The app


--- .class #id


## What's behind


--- .class #id

## Resulting plots


--- .class #id

## Conclusion


--- .class #id
